### ISSUE TITLE
Crashes with "No virtual method setOnTabSelectedListener"

### ISSUE THREAD

**Issue by peterhav** [1gravity/Android-ContactPicker#41]
I'm using this libray in my app, but recently it started to crash with this exception:

```
java.lang.NoSuchMethodError: No virtual method setOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/com.petermanapps.atcloud-YL97fZYcIM1aCE1xeiou9g==/split_lib_dependencies_apk.apk)
        at com.onegravity.contactpicker.core.ContactPickerActivity.onCreate(ContactPickerActivity.java:357)
```

This seems to have to do with this post: https://stackoverflow.com/questions/38498788/setontabselectedlistener-is-deprecated

Unfortunately I do not have the time to investigate this any further at the moment.

**Comment by LordParsley** [comment]
I see this issue is resolved on @yashpalraj 's fork in https://github.com/yashpalraj/Android-ContactPicker/commit/b2f3e2ee2e56de1ebd3c7600ecb44d8ba56aa938.

I've created a PR here based on that work which migrates to AndroidX: https://github.com/1gravity/Android-ContactPicker/pull/45

**Comment by dariomolina93** [comment]
Can an admin push the above branch into master? I'm currently still facing this issue and i see the fix is in an open pull request.

**Comment by ahmedamirss** [comment]
Can someone authorized please review and merge the PR by @LordParsley.
